### ISSUE TITLE
another way too reshade

### ISSUE THREAD

**Issue by Aokromes** [Marotheit/A-Guide-to-Modernizing-the-WotLK-Client#1]
maybe you want to add reshade to the list.

https://www.youtube.com/watch?v=5eqSl4GdFkY

**Comment by Marotheit** [comment]
I added a section on installing ReShade. I am hesitant to recommend any presets as most of them look over saturated to me (it all comes down to personal preference in the end, anyway...).

I appreciate everyone's patience, I was in the middle of a very long move recently so it took a while for me to update anything.

**Comment by Aokromes** [comment]
oh don't worry, i have issues opened for years on some places lol thx for update.
