### ISSUE TITLE
Cataclysm music + Legion Dalaran Music

### ISSUE THREAD

**Issue by Zergei** [Marotheit/A-Guide-to-Modernizing-the-WotLK-Client#3]
i found a patch that besides changing Classic Music to Cataclysm Music also changes Dalaran Music for the used in Legion https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-model-editing/648793-cata-music-overhaul-3-3-5-wotlk-client.html

**Comment by Marotheit** [comment]
Upon inspection of the patches, Leeviathan's patch is more thorough, so I would recommend sticking with that patch despite it's larger file size.

**Comment by Zergei** [comment]
you should check the patch thought i change it and there is no music except for the cities
