### ISSUE TITLE
YetAnotherWaterPatch alternative patch request

### ISSUE THREAD

**Issue by Zergei** [Marotheit/A-Guide-to-Modernizing-the-WotLK-Client#5]
sorry for this but wanted to request it is it possible to make an alternative to YetAnotherWaterPatch but without the water textures my reason behind this request is because the water textures of your patch are good but has no animations on them or they are not much noticeable at first glance comparing to this modders water patch https://forum.uwow.biz/threads/cvpatch-collection-visual-patch-lich-king-3-3-5.296264/

this is just a request nothing more
thanks in advance

**Comment by Marotheit** [comment]
There's a give and take with this one. The animations that feature big waves function in both the ocean, where they look great, and in smaller lakes, where they look unnatural.

I could look into making a YetAnotherWaterPatch with the waves included, but I'm waiting for Reznik to release the newest version of WotLK Boost so I can import his water lighting colors as well.

**Comment by Parliamentarian** [comment]
Heres my WOTLK folder with hd models and water mod that i've extensively tested.
It uses basic water for a lot of the smaller water bodies and also doesn't give a random crash when you are between Dalaran and Icecrown. 

My folder has the native mac app in it too which works on mac as well if you are using any OS older than Catalina. Tested mainly on high sierra.

Has HD models and textures and everything is working 100% yet still keeps the wotlk feel.

Look in /DATA/GFX MODS if you are only interested in the water mod or individual mods.

you can add .off as the file extension after the .mpq to turn them off or just drag them to the disabled folder.

https://mega.nz/folder/lgxS0b7b#CMQCSbbpvziprMUhljOEjg

**Comment by Parliamentarian** [comment]
> sorry for this but wanted to request it is it possible to make an alternative to YetAnotherWaterPatch but without the water textures my reason behind this request is because the water textures of your patch are good but has no animations on them or they are not much noticeable at first glance comparing to this modders water patch https://forum.uwow.biz/threads/cvpatch-collection-visual-patch-lich-king-3-3-5.296264/
> 
> this is just a request nothing more thanks in advance

Heres my WOTLK folder with hd models and water mod that i've extensively tested.
It uses basic water for a lot of the smaller water bodies and also doesn't give a random crash when you are between Dalaran and Icecrown.

My folder has the native mac app in it too which works on mac as well if you are using any OS older than Catalina. Tested mainly on high sierra.

Has HD models and textures and everything is working 100% yet still keeps the wotlk feel.

Look in /DATA/GFX MODS if you are only interested in the water mod or individual mods.

you can add .off as the file extension after the .mpq to turn them off or just drag them to the disabled folder.

https://mega.nz/folder/lgxS0b7b#CMQCSbbpvziprMUhljOEjg

**Comment by Zergei** [comment]
> > sorry for this but wanted to request it is it possible to make an alternative to YetAnotherWaterPatch but without the water textures my reason behind this request is because the water textures of your patch are good but has no animations on them or they are not much noticeable at first glance comparing to this modders water patch https://forum.uwow.biz/threads/cvpatch-collection-visual-patch-lich-king-3-3-5.296264/
> > this is just a request nothing more thanks in advance
> 
> Heres my WOTLK folder with hd models and water mod that i've extensively tested. It uses basic water for a lot of the smaller water bodies and also doesn't give a random crash when you are between Dalaran and Icecrown.
> 
> My folder has the native mac app in it too which works on mac as well if you are using any OS older than Catalina. Tested mainly on high sierra.
> 
> Has HD models and textures and everything is working 100% yet still keeps the wotlk feel.
> 
> Look in /DATA/GFX MODS if you are only interested in the water mod or individual mods.
> 
> you can add .off as the file extension after the .mpq to turn them off or just drag them to the disabled folder.
> 
> https://mega.nz/folder/lgxS0b7b#CMQCSbbpvziprMUhljOEjg

it requires a password XD

**Comment by Zergei** [comment]
> ###
> [Jun 23, 2024](#issuecomment-2185148518)

![image](https://github.com/Marotheit/A-Guide-to-Modernizing-the-WotLK-Client/assets/1284407/74b6dfad-e411-4017-a390-1b8c5d8dc924)

**Comment by Marotheit** [comment]
I will update this guide later tonight with a link to acquiring the Water Patch from the Project Epoch community, as it's very well made and has better support from a larger team. Although YetAnotherWaterPatch will continue to be usable, I would recommend switching to the Project Epoch patch going forward.
