### ISSUE TITLE
game crashes when talking to almost any goblin

### ISSUE THREAD

**Issue by dewmguy** [Marotheit/A-Guide-to-Modernizing-the-WotLK-Client#6]
title.

with a fresh 3.3.5 client, installing the mods recommended, and applying all the settings as outlined in the game; talking with just about any goblin in the game causes a client crash. i haven't yet tried to disable each patch to find the culprit but i have a feeling it's the creature texture patch

**Comment by Marotheit** [comment]
Upon testing, it seems removing patch-H.MPQ (Leeviathan and vvladoon's Updated Character Models) is the culprit. Removing the patch allowed me to speak to everyone in Booty Bay without issue.

I will add a disclaimer to the download letting people know. There's not an alternative at the moment (waiting for Reznik to release the next version of WotLK Boost for some much needed patch updates).
