### ISSUE TITLE
Spell animation patch issue

### ISSUE THREAD

**Issue by dubbyz** [Marotheit/A-Guide-to-Modernizing-the-WotLK-Client#8]
With flamestrike there is no more fire on the ground indicating where damage is done when people walk in it on the ground, is there any way to fix this or to easily identify which of the files in the mpq are the flamestrike animation so i can remove it and use the original one?
Since it would be kind of hard to filter through like 1700 files to see which one is the flamestrike one lol

**Comment by Marotheit** [comment]
I will update this guide with a link to Reznik's WotLK Boost patch as it has better compatibility across the board, including spell animations.
